# Generated by Django 5.2.17 on 2026-08-17 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('phishing_probability', models.FloatField()),
                ('detected_threat_count', models.IntegerField()),
                ('analysis_data', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
